lvgl:
  default_font: roboto_lg
  pages:
    - id: weather_forecast
      widgets:
        - obj:
            align: CENTER
            width: 320
            height: 240
            pad_all: 10
            layout:
              pad_column: 0
              type: GRID
              grid_rows: [FR(25), FR(20), FR(20), FR(20), FR(15)]
              grid_columns: [FR(50), FR(10), FR(40)]
            widgets:
              - image:
                  id: img_weather_forecast_icon
                  src: sunny
                  grid_cell_row_pos: 0
                  grid_cell_row_span: 3
                  grid_cell_column_pos: 0
                  grid_cell_x_align: CENTER
                  grid_cell_y_align: CENTER

              - label:
                  text: "12-03-2024"
                  id: lbl_weather_forecast_condition_date
                  text_font: roboto_xlg
                  text_align: CENTER
                  text_color: teal
                  grid_cell_row_pos: 0
                  grid_cell_column_pos: 1
                  grid_cell_column_span: 2
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: CENTER

              - label:
                  text: "\U000F050F"
                  text_font: icons_md
                  text_align: CENTER
                  grid_cell_row_pos: 1
                  grid_cell_column_pos: 1
                  grid_cell_x_align: CENTER
                  grid_cell_y_align: CENTER
              
              - label:
                  text: "-- \u00B0F"
                  id: lbl_weather_forecast_condition_temperature
                  text_align: CENTER
                  grid_cell_row_pos: 1
                  grid_cell_column_pos: 2
                  grid_cell_x_align: START
                  grid_cell_y_align: CENTER

              - label:
                  text: "\U000F058E"
                  text_font: icons_md
                  text_align: CENTER
                  grid_cell_row_pos: 2
                  grid_cell_column_pos: 1
                  grid_cell_x_align: CENTER
                  grid_cell_y_align: CENTER

              - label:
                  text: "--%"
                  id: lbl_weather_forecast_condition_humidity
                  text_align: CENTER
                  grid_cell_row_pos: 2
                  grid_cell_column_pos: 2
                  grid_cell_x_align: START
                  grid_cell_y_align: CENTER

              - label:
                  text: "LOADING..."
                  id: lbl_weather_forecast_condition_state
                  text_align: CENTER
                  text_font: roboto_md
                  grid_cell_row_pos: 3
                  grid_cell_column_pos: 0
                  grid_cell_column_span: 3
                  grid_cell_x_align: CENTER
                  grid_cell_y_align: CENTER

              - label:
                  text: "Last Update: 10:47"
                  id: lbl_weather_forecast_condition_last_updated
                  text_font: roboto_sm
                  text_align: CENTER
                  text_color: grey
                  grid_cell_row_pos: 4
                  grid_cell_column_pos: 0
                  grid_cell_column_span: 3
                  grid_cell_x_align: CENTER
                  grid_cell_y_align: CENTER

sensor:
  - id: weather_temperature
    platform: homeassistant
    entity_id: sensor.precipitation_station_temperature
    on_value:
      then:
        - lvgl.label.update:
            id: lbl_weather_forecast_condition_temperature
            text:
              format: "%.0f \u00B0F"
              args: [ 'x' ]

text:
  - platform: lvgl
    name: date
    widget: lbl_weather_forecast_condition_date
    mode: text
  - platform: lvgl
    name: temperature
    widget: lbl_weather_forecast_condition_temperature
    mode: text
  - platform: lvgl
    name: humidity
    widget: lbl_weather_forecast_condition_humidity
    mode: text
  - platform: lvgl
    name: last_updated
    widget: lbl_weather_forecast_condition_last_updated
    mode: text